spring:
  h2:
    console:
      enabled: true
      path: '/database'
  datasource:
    username: 'admin'
    password: 'admin'
    url: 'jdbc:h2:file:./database'
  jpa:
    hibernate:
      ddl-auto: 'validate'
  flyway:
    enabled: true
    baseline-on-migrate: true
  main:
    banner-mode: off
#TODO: create profiles: local, prod
server:
  error:
    include-stacktrace: never


